title: Einführung in empirische und experimentelle Forschungsmethoden
logo: http://www.presse.uni-wuerzburg.de/fileadmin/uniwue/ci/Logos/Pixelgrafiken/web/unilogo4cohne.png
description: Materialien für das Empra, Sommersemester 2018, Gruppe 08
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
