title: Einf체hrung in empirische und experimentelle Forschungsmethoden
logo: http://www.presse.uni-wuerzburg.de/fileadmin/uniwue/ci/Logos/Pixelgrafiken/web/uniwue4c.png
description: Materialien f체r das Empra, Sommersemester 2018, Gruppe 08, Universit채t W체rzburg
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
